// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: articles_feeds.sql

package db

import (
	"context"
)

const createArticleFeed = `-- name: CreateArticleFeed :one
INSERT INTO articles_feeds (id, article_id, feed_id)
VALUES (?, ?, ?)
RETURNING id, article_id, feed_id, is_read, created_at, modified_at
`

type CreateArticleFeedParams struct {
	ID        string `json:"id"`
	ArticleID string `json:"article_id"`
	FeedID    string `json:"feed_id"`
}

func (q *Queries) CreateArticleFeed(ctx context.Context, arg CreateArticleFeedParams) (ArticleFeed, error) {
	row := q.db.QueryRowContext(ctx, createArticleFeed, arg.ID, arg.ArticleID, arg.FeedID)
	var i ArticleFeed
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.FeedID,
		&i.IsRead,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const findArticleFeedsByArticleAndUser = `-- name: FindArticleFeedsByArticleAndUser :many
SELECT af.id, af.article_id, af.feed_id, af.is_read, af.created_at, af.modified_at
FROM articles_feeds af
JOIN feeds f ON f.id = af.feed_id
    AND f.user_id = ?
    AND f.status = 1
    AND f.removed_at IS NULL
WHERE af.article_id = ?
`

type FindArticleFeedsByArticleAndUserParams struct {
	UserID    string `json:"user_id"`
	ArticleID string `json:"article_id"`
}

func (q *Queries) FindArticleFeedsByArticleAndUser(ctx context.Context, arg FindArticleFeedsByArticleAndUserParams) ([]ArticleFeed, error) {
	rows, err := q.db.QueryContext(ctx, findArticleFeedsByArticleAndUser, arg.UserID, arg.ArticleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []ArticleFeed
	for rows.Next() {
		var i ArticleFeed
		if err := rows.Scan(
			&i.ID,
			&i.ArticleID,
			&i.FeedID,
			&i.IsRead,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markArticleAsReadForUser = `-- name: MarkArticleAsReadForUser :exec
UPDATE articles_feeds
SET is_read = 1, modified_at = CURRENT_TIMESTAMP
WHERE article_id = ?
  AND is_read = 0
  AND feed_id IN (
      SELECT id FROM feeds
      WHERE user_id = ? AND status = 1 AND removed_at IS NULL
  )
`

type MarkArticleAsReadForUserParams struct {
	ArticleID string `json:"article_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) MarkArticleAsReadForUser(ctx context.Context, arg MarkArticleAsReadForUserParams) error {
	_, err := q.db.ExecContext(ctx, markArticleAsReadForUser, arg.ArticleID, arg.UserID)
	return err
}
