// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: articles.sql

package db

import (
	"context"
)

const createArticle = `-- name: CreateArticle :one
INSERT INTO articles (id, title, content, url_original, keywords, source_id)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, status, title, content, url_original, keywords, source_id, created_at, modified_at, removed_at
`

type CreateArticleParams struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Content     string `json:"content"`
	UrlOriginal string `json:"url_original"`
	Keywords    string `json:"keywords"`
	SourceID    string `json:"source_id"`
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error) {
	row := q.db.QueryRowContext(ctx, createArticle,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.UrlOriginal,
		arg.Keywords,
		arg.SourceID,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Title,
		&i.Content,
		&i.UrlOriginal,
		&i.Keywords,
		&i.SourceID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.RemovedAt,
	)
	return i, err
}

const findArticleByID = `-- name: FindArticleByID :one
SELECT id, status, title, content, url_original, keywords, source_id, created_at, modified_at, removed_at FROM articles
WHERE id = ? AND status = 1 AND removed_at IS NULL
LIMIT 1
`

func (q *Queries) FindArticleByID(ctx context.Context, id string) (Article, error) {
	row := q.db.QueryRowContext(ctx, findArticleByID, id)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Title,
		&i.Content,
		&i.UrlOriginal,
		&i.Keywords,
		&i.SourceID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.RemovedAt,
	)
	return i, err
}

const findArticleByURLOriginal = `-- name: FindArticleByURLOriginal :one
SELECT id, status, title, content, url_original, keywords, source_id, created_at, modified_at, removed_at FROM articles
WHERE url_original = ? AND status = 1 AND removed_at IS NULL
LIMIT 1
`

func (q *Queries) FindArticleByURLOriginal(ctx context.Context, urlOriginal string) (Article, error) {
	row := q.db.QueryRowContext(ctx, findArticleByURLOriginal, urlOriginal)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Title,
		&i.Content,
		&i.UrlOriginal,
		&i.Keywords,
		&i.SourceID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.RemovedAt,
	)
	return i, err
}

const listArticles = `-- name: ListArticles :many
SELECT id, status, title, content, url_original, keywords, source_id, created_at, modified_at, removed_at FROM articles
WHERE status = 1 AND removed_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListArticles(ctx context.Context) ([]Article, error) {
	rows, err := q.db.QueryContext(ctx, listArticles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Title,
			&i.Content,
			&i.UrlOriginal,
			&i.Keywords,
			&i.SourceID,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.RemovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArticle = `-- name: UpdateArticle :one
UPDATE articles
SET title = ?, content = ?, url_original = ?, keywords = ?, modified_at = CURRENT_TIMESTAMP
WHERE id = ? AND status = 1 AND removed_at IS NULL
RETURNING id, status, title, content, url_original, keywords, source_id, created_at, modified_at, removed_at
`

type UpdateArticleParams struct {
	Title       string `json:"title"`
	Content     string `json:"content"`
	UrlOriginal string `json:"url_original"`
	Keywords    string `json:"keywords"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateArticle(ctx context.Context, arg UpdateArticleParams) (Article, error) {
	row := q.db.QueryRowContext(ctx, updateArticle,
		arg.Title,
		arg.Content,
		arg.UrlOriginal,
		arg.Keywords,
		arg.ID,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Title,
		&i.Content,
		&i.UrlOriginal,
		&i.Keywords,
		&i.SourceID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.RemovedAt,
	)
	return i, err
}

const softDeleteArticle = `-- name: SoftDeleteArticle :exec
UPDATE articles
SET status = 0, removed_at = CURRENT_TIMESTAMP, modified_at = CURRENT_TIMESTAMP
WHERE id = ? AND removed_at IS NULL
`

func (q *Queries) SoftDeleteArticle(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, softDeleteArticle, id)
	return err
}

const softDeleteArticlesBySourceID = `-- name: SoftDeleteArticlesBySourceID :exec
UPDATE articles
SET status = 0, removed_at = CURRENT_TIMESTAMP, modified_at = CURRENT_TIMESTAMP
WHERE source_id = ? AND removed_at IS NULL
`

func (q *Queries) SoftDeleteArticlesBySourceID(ctx context.Context, sourceID string) error {
	_, err := q.db.ExecContext(ctx, softDeleteArticlesBySourceID, sourceID)
	return err
}
