// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: articles.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	utctime "github.com/nathanap/news-feed-backend/services/utctime"
)

const countArticles = `-- name: CountArticles :one
SELECT COUNT(*) FROM articles
WHERE status = TRUE AND removed_at IS NULL
  AND ($1::text IS NULL OR strpos(lower(url_original), lower($1::text)) > 0)
`

// Total matching rows for the ListArticles page, feeding pagination.total_count.
// Its filters MUST mirror ListArticles above, or the envelope lies about the total.
func (q *Queries) CountArticles(ctx context.Context, url sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countArticles, url)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createArticle = `-- name: CreateArticle :one
INSERT INTO articles (id, title, content, url_original, keywords, source_id, language_original)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, status, title, content, url_original, keywords, source_id, language_original, created_at, modified_at, removed_at
`

type CreateArticleParams struct {
	ID               string          `json:"id"`
	Title            string          `json:"title"`
	Content          string          `json:"content"`
	UrlOriginal      string          `json:"url_original"`
	Keywords         json.RawMessage `json:"keywords"`
	SourceID         string          `json:"source_id"`
	LanguageOriginal sql.NullString  `json:"language_original"`
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error) {
	row := q.db.QueryRowContext(ctx, createArticle,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.UrlOriginal,
		arg.Keywords,
		arg.SourceID,
		arg.LanguageOriginal,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Title,
		&i.Content,
		&i.UrlOriginal,
		&i.Keywords,
		&i.SourceID,
		&i.LanguageOriginal,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.RemovedAt,
	)
	return i, err
}

const findArticleByID = `-- name: FindArticleByID :one
SELECT id, status, title, content, url_original, keywords, source_id, language_original, created_at, modified_at, removed_at FROM articles
WHERE id = $1 AND status = TRUE AND removed_at IS NULL
LIMIT 1
`

func (q *Queries) FindArticleByID(ctx context.Context, id string) (Article, error) {
	row := q.db.QueryRowContext(ctx, findArticleByID, id)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Title,
		&i.Content,
		&i.UrlOriginal,
		&i.Keywords,
		&i.SourceID,
		&i.LanguageOriginal,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.RemovedAt,
	)
	return i, err
}

const findArticleByURLOriginal = `-- name: FindArticleByURLOriginal :one
SELECT id, status, title, content, url_original, keywords, source_id, language_original, created_at, modified_at, removed_at FROM articles
WHERE url_original = $1 AND status = TRUE AND removed_at IS NULL
LIMIT 1
`

func (q *Queries) FindArticleByURLOriginal(ctx context.Context, urlOriginal string) (Article, error) {
	row := q.db.QueryRowContext(ctx, findArticleByURLOriginal, urlOriginal)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Title,
		&i.Content,
		&i.UrlOriginal,
		&i.Keywords,
		&i.SourceID,
		&i.LanguageOriginal,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.RemovedAt,
	)
	return i, err
}

const listAllArticles = `-- name: ListAllArticles :many
SELECT id, status, title, content, url_original, keywords, source_id, language_original, created_at, modified_at, removed_at FROM articles
WHERE status = TRUE AND removed_at IS NULL
ORDER BY created_at DESC, id DESC
`

// Every active article, unfiltered and unpaginated, for the dev seed scripts (which need the whole
// set to build article/feed associations). See ListAllSources for why this is separate from the
// paginated ListArticles that serves HTTP.
func (q *Queries) ListAllArticles(ctx context.Context) ([]Article, error) {
	rows, err := q.db.QueryContext(ctx, listAllArticles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Title,
			&i.Content,
			&i.UrlOriginal,
			&i.Keywords,
			&i.SourceID,
			&i.LanguageOriginal,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.RemovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticles = `-- name: ListArticles :many
SELECT id, status, title, content, url_original, keywords, source_id, language_original, created_at, modified_at, removed_at FROM articles
WHERE status = TRUE AND removed_at IS NULL
  AND ($1::text IS NULL OR strpos(lower(url_original), lower($1::text)) > 0)
ORDER BY created_at DESC, id DESC
LIMIT $3 OFFSET $2
`

type ListArticlesParams struct {
	Url        sql.NullString `json:"url"`
	PageOffset int32          `json:"page_offset"`
	PageLimit  int32          `json:"page_limit"`
}

// Lists the active articles for GET /v1/articles, filtered and paginated in SQL.
// The url filter is optional: a NULL param means "no filter" (sqlc.narg), so one query serves both
// the filtered and the unfiltered case. strpos(lower(a), lower(b)) > 0 is a literal case-insensitive
// substring test -- deliberately not ILIKE '%...%', which would let a user's % or _ act as wildcards.
// Neither can use an index (leading wildcard); pg_trgm is the path if that ever matters.
// id breaks created_at ties so the ordering is total: without it, rows written in the same CRON
// batch share a timestamp and LIMIT/OFFSET could repeat or skip one across pages. id is a UUIDv7,
// so it sorts by creation time and the tie-break stays chronological.
// CountArticles below MUST keep the same filters.
func (q *Queries) ListArticles(ctx context.Context, arg ListArticlesParams) ([]Article, error) {
	rows, err := q.db.QueryContext(ctx, listArticles, arg.Url, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Title,
			&i.Content,
			&i.UrlOriginal,
			&i.Keywords,
			&i.SourceID,
			&i.LanguageOriginal,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.RemovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteArticle = `-- name: SoftDeleteArticle :exec
UPDATE articles
SET status = FALSE, removed_at = CURRENT_TIMESTAMP, modified_at = CURRENT_TIMESTAMP
WHERE id = $1 AND removed_at IS NULL
`

func (q *Queries) SoftDeleteArticle(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, softDeleteArticle, id)
	return err
}

const softDeleteArticlesBySourceID = `-- name: SoftDeleteArticlesBySourceID :exec
UPDATE articles
SET status = FALSE, removed_at = CURRENT_TIMESTAMP, modified_at = CURRENT_TIMESTAMP
WHERE source_id = $1 AND removed_at IS NULL
`

func (q *Queries) SoftDeleteArticlesBySourceID(ctx context.Context, sourceID string) error {
	_, err := q.db.ExecContext(ctx, softDeleteArticlesBySourceID, sourceID)
	return err
}

const suggestPopularKeywords = `-- name: SuggestPopularKeywords :many
SELECT kw.value::text AS keyword, COUNT(*) AS occurrences
FROM articles a
CROSS JOIN LATERAL jsonb_array_elements_text(a.keywords) AS kw(value)
WHERE a.status = TRUE AND a.removed_at IS NULL
  AND a.created_at >= $1::timestamptz
  AND kw.value <> ALL(ARRAY(SELECT jsonb_array_elements_text($2::jsonb)))
GROUP BY kw.value
ORDER BY occurrences DESC, keyword ASC
LIMIT $3
`

type SuggestPopularKeywordsParams struct {
	Since       utctime.Time    `json:"since"`
	Exclude     json.RawMessage `json:"exclude"`
	ResultLimit int32           `json:"result_limit"`
}

type SuggestPopularKeywordsRow struct {
	Keyword     string `json:"keyword"`
	Occurrences int64  `json:"occurrences"`
}

// Keyword suggestions, "popular" strategy: the keywords carried by the most active articles inside a
// recency window, for the feed-building keyword-suggestion endpoint. This is the fallback path (used
// when nothing is selected yet, or when the "related" query came back empty), so it must always be
// able to return something as long as the window holds any article.
// LATERAL expands each active article's keyword array into rows; COUNT per distinct keyword is how
// many articles carry it (keywords are unique within an article, so one row per article-keyword).
// The window (created_at >= since) is what makes "popular" mean "popular right now" and keeps the
// full-table aggregation bounded; the caller passes the epoch when the window is disabled.
// exclude is the caller's already-picked keywords as a JSON array (empty = exclude nothing, since
// value <> ALL(empty) is TRUE); no point suggesting a keyword the user already has.
// Ordered by count, then keyword for a stable, deterministic tie-break (same lesson as the 0.38 lists).
func (q *Queries) SuggestPopularKeywords(ctx context.Context, arg SuggestPopularKeywordsParams) ([]SuggestPopularKeywordsRow, error) {
	rows, err := q.db.QueryContext(ctx, suggestPopularKeywords, arg.Since, arg.Exclude, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SuggestPopularKeywordsRow
	for rows.Next() {
		var i SuggestPopularKeywordsRow
		if err := rows.Scan(&i.Keyword, &i.Occurrences); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const suggestRelatedKeywords = `-- name: SuggestRelatedKeywords :many
SELECT kw.value::text AS keyword, COUNT(*) AS occurrences
FROM articles a
CROSS JOIN LATERAL jsonb_array_elements_text(a.keywords) AS kw(value)
WHERE a.status = TRUE AND a.removed_at IS NULL
  AND a.keywords ?| ARRAY(SELECT jsonb_array_elements_text($1::jsonb))
  AND kw.value <> ALL(ARRAY(SELECT jsonb_array_elements_text($1::jsonb)))
GROUP BY kw.value
ORDER BY occurrences DESC, keyword ASC
LIMIT $2
`

type SuggestRelatedKeywordsParams struct {
	Selected    json.RawMessage `json:"selected"`
	ResultLimit int32           `json:"result_limit"`
}

type SuggestRelatedKeywordsRow struct {
	Keyword     string `json:"keyword"`
	Occurrences int64  `json:"occurrences"`
}

// Keyword suggestions, "related" strategy: keywords that co-occur with the ones the user already
// picked. Narrows to articles that carry ANY selected keyword (keywords ?| selected), then counts
// the OTHER keywords those articles carry. Deliberately not windowed (unlike popular): relatedness is
// topical, not temporal, and a window would only make the empty-result fallback fire more often for a
// niche pick.
// The `?|` predicate is what reaches idx_articles_keywords (GIN): it is applied as a row filter that
// narrows which articles get expanded, exactly the shape the 0.37.3 review established. Keep it in
// sync with that index. selected drives both the narrowing (which articles) and the exclusion (never
// suggest back a keyword the user already picked).
// selected is a JSON array of lowercase keywords. Same count/order semantics as SuggestPopularKeywords.
func (q *Queries) SuggestRelatedKeywords(ctx context.Context, arg SuggestRelatedKeywordsParams) ([]SuggestRelatedKeywordsRow, error) {
	rows, err := q.db.QueryContext(ctx, suggestRelatedKeywords, arg.Selected, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SuggestRelatedKeywordsRow
	for rows.Next() {
		var i SuggestRelatedKeywordsRow
		if err := rows.Scan(&i.Keyword, &i.Occurrences); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArticle = `-- name: UpdateArticle :one
UPDATE articles
SET title = $1, content = $2, url_original = $3, keywords = $4, language_original = $5, modified_at = CURRENT_TIMESTAMP
WHERE id = $6 AND status = TRUE AND removed_at IS NULL
RETURNING id, status, title, content, url_original, keywords, source_id, language_original, created_at, modified_at, removed_at
`

type UpdateArticleParams struct {
	Title            string          `json:"title"`
	Content          string          `json:"content"`
	UrlOriginal      string          `json:"url_original"`
	Keywords         json.RawMessage `json:"keywords"`
	LanguageOriginal sql.NullString  `json:"language_original"`
	ID               string          `json:"id"`
}

func (q *Queries) UpdateArticle(ctx context.Context, arg UpdateArticleParams) (Article, error) {
	row := q.db.QueryRowContext(ctx, updateArticle,
		arg.Title,
		arg.Content,
		arg.UrlOriginal,
		arg.Keywords,
		arg.LanguageOriginal,
		arg.ID,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Title,
		&i.Content,
		&i.UrlOriginal,
		&i.Keywords,
		&i.SourceID,
		&i.LanguageOriginal,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.RemovedAt,
	)
	return i, err
}

const updateArticleContent = `-- name: UpdateArticleContent :exec
UPDATE articles
SET content = $1, modified_at = CURRENT_TIMESTAMP
WHERE id = $2 AND status = TRUE AND removed_at IS NULL
`

type UpdateArticleContentParams struct {
	Content string `json:"content"`
	ID      string `json:"id"`
}

// Overwrites only the body, for the 0.45 treatment DB step: right after an article is stored, its
// anchors are rewritten to outbound-link ids and the body is written back. Keeps title/keywords/etc.
// untouched (unlike UpdateArticle). Runs inside the same transaction as the insert.
func (q *Queries) UpdateArticleContent(ctx context.Context, arg UpdateArticleContentParams) error {
	_, err := q.db.ExecContext(ctx, updateArticleContent, arg.Content, arg.ID)
	return err
}
