// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: article_outbound_links.sql

package db

import (
	"context"

	"github.com/lib/pq"
)

const createArticleOutboundLink = `-- name: CreateArticleOutboundLink :one
INSERT INTO article_outbound_links (id, article_id, href)
VALUES ($1, $2, $3)
RETURNING id, article_id, href, created_at, modified_at
`

type CreateArticleOutboundLinkParams struct {
	ID        string `json:"id"`
	ArticleID string `json:"article_id"`
	Href      string `json:"href"`
}

// One row per distinct href found in a freshly persisted article body (see the outboundlinks service).
// href is the real target: an internal link as the literal token `{CLIENT_URL}/articles/{id}`, an
// external link literally. The body stores this row's id in the anchor, never the URL.
func (q *Queries) CreateArticleOutboundLink(ctx context.Context, arg CreateArticleOutboundLinkParams) (ArticleOutboundLink, error) {
	row := q.db.QueryRowContext(ctx, createArticleOutboundLink, arg.ID, arg.ArticleID, arg.Href)
	var i ArticleOutboundLink
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.Href,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const deleteArticleOutboundLinksByArticleID = `-- name: DeleteArticleOutboundLinksByArticleID :exec
DELETE FROM article_outbound_links
WHERE article_id = $1
`

// Hard-delete cascade for an article hard-remove. Dormant today (articles are only soft-removed) but
// kept ready in code, per the project's cascade philosophy.
func (q *Queries) DeleteArticleOutboundLinksByArticleID(ctx context.Context, articleID string) error {
	_, err := q.db.ExecContext(ctx, deleteArticleOutboundLinksByArticleID, articleID)
	return err
}

const listArticleOutboundLinksByArticleIDs = `-- name: ListArticleOutboundLinksByArticleIDs :many
SELECT id, article_id, href, created_at, modified_at FROM article_outbound_links
WHERE article_id = ANY($1::text[])
`

// Every outbound link of the given articles, in one batch, for the read-time swap. The listing/read
// endpoints pass the ids of the whole page here (never one query per article - no N+1).
// Stays on ANY(...::text[]) even though it makes sqlc emit pq.Array, which is the only reason lib/pq
// is still a dependency alongside the real driver (pgx). Do NOT "clean this up" with sqlc.slice:
// tried in 0.46 and it is broken for the postgresql engine - sqlc renders the placeholder as `$1`,
// losing the /*SLICE:*/ marker its own generated strings.Replace looks for, and then builds MySQL
// style `?` placeholders. Result compiles and passes any test that sends a single id, but fails at
// runtime as soon as a page carries two (bind message supplies N parameters, statement requires 1).
func (q *Queries) ListArticleOutboundLinksByArticleIDs(ctx context.Context, articleIds []string) ([]ArticleOutboundLink, error) {
	rows, err := q.db.QueryContext(ctx, listArticleOutboundLinksByArticleIDs, pq.Array(articleIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArticleOutboundLink
	for rows.Next() {
		var i ArticleOutboundLink
		if err := rows.Scan(
			&i.ID,
			&i.ArticleID,
			&i.Href,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retargetArticleOutboundLinksByHref = `-- name: RetargetArticleOutboundLinksByHref :exec
UPDATE article_outbound_links
SET href = $1, modified_at = CURRENT_TIMESTAMP
WHERE href = $2
`

type RetargetArticleOutboundLinksByHrefParams struct {
	NewHref string `json:"new_href"`
	OldHref string `json:"old_href"`
}

// Repoints every row currently pointing at old_href to new_href. Two callers, both matching by exact
// href (idx_article_outbound_links_href):
//   - retroactive linking: when article B is persisted, old_href = B.url_original, new_href =
//     `{CLIENT_URL}/articles/{B.id}` — older articles that linked B's external URL now open internally.
//   - pre-remove cleanup: before an article L is removed, old_href = `{CLIENT_URL}/articles/{L.id}`,
//     new_href = L.url_original — links pointing at the vanishing internal page fall back to the source.
func (q *Queries) RetargetArticleOutboundLinksByHref(ctx context.Context, arg RetargetArticleOutboundLinksByHrefParams) error {
	_, err := q.db.ExecContext(ctx, retargetArticleOutboundLinksByHref, arg.NewHref, arg.OldHref)
	return err
}

const retargetArticleOutboundLinksBySourceID = `-- name: RetargetArticleOutboundLinksBySourceID :exec
UPDATE article_outbound_links l
SET href = a.url_original, modified_at = CURRENT_TIMESTAMP
FROM articles a
WHERE a.source_id = $1
  AND a.removed_at IS NULL
  AND l.href = $2::text || a.id
`

type RetargetArticleOutboundLinksBySourceIDParams struct {
	SourceID           string `json:"source_id"`
	InternalHrefPrefix string `json:"internal_href_prefix"`
}

// Cascade counterpart of RetargetArticleOutboundLinksByHref, for the source soft-delete (0.48.3).
// Soft-deleting a source cascades to its articles, and a cascaded article is still a removed article:
// every outbound link pointing at its internal page has to fall back to the source URL, or older
// articles keep anchors to a page that answers 404. The single-article delete path had this since
// 0.46.1; the cascade path did not, which is the gap this closes.
//
// Set-based on purpose: one statement instead of one Retarget per article. A source can own a lot of
// articles, and an N+1 inside the deletion transaction is the wrong shape.
//
// internal_href_prefix is `{CLIENT_URL}/articles/` supplied by Go (outboundlinks.InternalHrefPrefix),
// so the token format stays owned by the outboundlinks package instead of being duplicated in SQL.
func (q *Queries) RetargetArticleOutboundLinksBySourceID(ctx context.Context, arg RetargetArticleOutboundLinksBySourceIDParams) error {
	_, err := q.db.ExecContext(ctx, retargetArticleOutboundLinksBySourceID, arg.SourceID, arg.InternalHrefPrefix)
	return err
}
