// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feeds.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	utctime "github.com/nathanap/news-feed-backend/services/utctime"
)

const countActiveFeedsByUser = `-- name: CountActiveFeedsByUser :one
SELECT COUNT(*) FROM feeds
WHERE user_id = $1 AND status = TRUE AND removed_at IS NULL
`

// Counts every active feed of a user, enforcing the max-active-feeds business rule at creation
// time. Intentionally unfiltered: the limit is about how many feeds exist, not about a search.
func (q *Queries) CountActiveFeedsByUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveFeedsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFeedsByUser = `-- name: CountFeedsByUser :one
SELECT COUNT(*) FROM feeds
WHERE user_id = $1 AND status = TRUE AND removed_at IS NULL
  AND ($2::text IS NULL OR strpos(lower(name), lower($2::text)) > 0)
`

type CountFeedsByUserParams struct {
	UserID string         `json:"user_id"`
	Name   sql.NullString `json:"name"`
}

// Total matching rows for the ListFeedsByUser page, feeding pagination.total_count.
// Its filters MUST mirror ListFeedsByUser above, or the envelope lies about the total.
// NOTE: this is NOT the query that guards the 5-active-feeds-per-user rule -- that one is
// CountActiveFeedsByUser below, which must never see a name filter.
func (q *Queries) CountFeedsByUser(ctx context.Context, arg CountFeedsByUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFeedsByUser, arg.UserID, arg.Name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds (id, name, keywords, user_id)
VALUES ($1, $2, $3, $4)
RETURNING id, status, name, keywords, user_id, created_at, modified_at, removed_at
`

type CreateFeedParams struct {
	ID       string          `json:"id"`
	Name     string          `json:"name"`
	Keywords json.RawMessage `json:"keywords"`
	UserID   string          `json:"user_id"`
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed,
		arg.ID,
		arg.Name,
		arg.Keywords,
		arg.UserID,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Name,
		&i.Keywords,
		&i.UserID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.RemovedAt,
	)
	return i, err
}

const findCandidateFeedsByKeywords = `-- name: FindCandidateFeedsByKeywords :many
SELECT f.id, f.status, f.name, f.keywords, f.user_id, f.created_at, f.modified_at, f.removed_at,
       COUNT(DISTINCT fk.value) AS overlap_count
FROM feeds f
CROSS JOIN LATERAL jsonb_array_elements_text(f.keywords) AS fk(value)
JOIN jsonb_array_elements_text($1::jsonb) AS ak(value) ON ak.value = fk.value
WHERE f.status = TRUE AND f.removed_at IS NULL
  AND f.keywords ?| ARRAY(SELECT jsonb_array_elements_text($1::jsonb))
GROUP BY f.id
`

type FindCandidateFeedsByKeywordsRow struct {
	ID           string           `json:"id"`
	Status       bool             `json:"status"`
	Name         string           `json:"name"`
	Keywords     json.RawMessage  `json:"keywords"`
	UserID       string           `json:"user_id"`
	CreatedAt    utctime.Time     `json:"created_at"`
	ModifiedAt   utctime.NullTime `json:"modified_at"`
	RemovedAt    utctime.NullTime `json:"removed_at"`
	OverlapCount int64            `json:"overlap_count"`
}

// Judgement layer 1 (keyword overlap): returns every active feed (of any user) that shares at
// least one keyword with the article, along with overlap_count (how many distinct keywords matched).
// Both sides are JSONB arrays of lowercase strings, so jsonb_array_elements_text expands each into
// rows and the join matches on exact keyword equality. The LATERAL is what lets the expansion of
// f.keywords reference the feed row being scanned; the article's side does not depend on the row, so
// it is a plain join. GROUP BY collapses a feed to one row and COUNT gives its overlap (grouping by
// f.id alone is valid because it is the primary key, so the other f.* columns are functionally
// dependent on it). The overlap feeds the triage (auto-associate / discard / send-to-AI) in layer 2.
// The parameter is the article's keywords as a JSON array.
//
// The `?|` predicate ("does f.keywords contain ANY of these keys") is what makes idx_feeds_keywords
// (GIN) usable: an index is matched by OPERATOR, and expanding a column through
// jsonb_array_elements_text in a LATERAL is a function call on every row, which no index can serve.
// Without it the planner reads every active feed of every user and expands its keywords just to
// throw almost all of them away (measured on 60k feeds: 428ms/10.2k buffers versus 22ms/836 with it,
// where it becomes a Bitmap Index Scan on idx_feeds_keywords).
//
// It is logically redundant with the join below (a feed with zero shared keywords produces no row
// either way), so it cannot change the result set - it only lets the planner discard non-candidates
// before the expensive expansion. It must be kept in sync with the join's matching rule: both sides
// compare the same lowercase text keys.
func (q *Queries) FindCandidateFeedsByKeywords(ctx context.Context, keywords json.RawMessage) ([]FindCandidateFeedsByKeywordsRow, error) {
	rows, err := q.db.QueryContext(ctx, findCandidateFeedsByKeywords, keywords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindCandidateFeedsByKeywordsRow
	for rows.Next() {
		var i FindCandidateFeedsByKeywordsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Name,
			&i.Keywords,
			&i.UserID,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.RemovedAt,
			&i.OverlapCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findFeedByIDAndUser = `-- name: FindFeedByIDAndUser :one
SELECT id, status, name, keywords, user_id, created_at, modified_at, removed_at FROM feeds
WHERE id = $1 AND user_id = $2 AND status = TRUE AND removed_at IS NULL
LIMIT 1
`

type FindFeedByIDAndUserParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) FindFeedByIDAndUser(ctx context.Context, arg FindFeedByIDAndUserParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, findFeedByIDAndUser, arg.ID, arg.UserID)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Name,
		&i.Keywords,
		&i.UserID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.RemovedAt,
	)
	return i, err
}

const listAllFeedsByUser = `-- name: ListAllFeedsByUser :many
SELECT id, status, name, keywords, user_id, created_at, modified_at, removed_at FROM feeds
WHERE user_id = $1 AND status = TRUE AND removed_at IS NULL
ORDER BY created_at DESC, id DESC
`

// Every active feed of a user, unfiltered and unpaginated, for the dev seed scripts. See
// ListAllSources for why this is separate from the paginated ListFeedsByUser that serves HTTP.
func (q *Queries) ListAllFeedsByUser(ctx context.Context, userID string) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, listAllFeedsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Name,
			&i.Keywords,
			&i.UserID,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.RemovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedsByUser = `-- name: ListFeedsByUser :many
SELECT id, status, name, keywords, user_id, created_at, modified_at, removed_at FROM feeds
WHERE user_id = $1 AND status = TRUE AND removed_at IS NULL
  AND ($2::text IS NULL OR strpos(lower(name), lower($2::text)) > 0)
ORDER BY created_at DESC, id DESC
LIMIT $4 OFFSET $3
`

type ListFeedsByUserParams struct {
	UserID     string         `json:"user_id"`
	Name       sql.NullString `json:"name"`
	PageOffset int32          `json:"page_offset"`
	PageLimit  int32          `json:"page_limit"`
}

// Lists the requesting user's active feeds for GET /v1/feeds, filtered and paginated in SQL.
// The name filter is optional (NULL = not applied). See ListArticles for why strpos over ILIKE and
// why id breaks the created_at tie. CountFeedsByUser below MUST keep the same filters.
func (q *Queries) ListFeedsByUser(ctx context.Context, arg ListFeedsByUserParams) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, listFeedsByUser,
		arg.UserID,
		arg.Name,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Name,
			&i.Keywords,
			&i.UserID,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.RemovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteFeedByIDAndUser = `-- name: SoftDeleteFeedByIDAndUser :exec
UPDATE feeds
SET status = FALSE, removed_at = CURRENT_TIMESTAMP, modified_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2 AND removed_at IS NULL
`

type SoftDeleteFeedByIDAndUserParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) SoftDeleteFeedByIDAndUser(ctx context.Context, arg SoftDeleteFeedByIDAndUserParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteFeedByIDAndUser, arg.ID, arg.UserID)
	return err
}

const softDeleteFeedsByUser = `-- name: SoftDeleteFeedsByUser :exec
UPDATE feeds
SET status = FALSE, removed_at = CURRENT_TIMESTAMP, modified_at = CURRENT_TIMESTAMP
WHERE user_id = $1 AND removed_at IS NULL
`

func (q *Queries) SoftDeleteFeedsByUser(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, softDeleteFeedsByUser, userID)
	return err
}

const updateFeedByIDAndUser = `-- name: UpdateFeedByIDAndUser :one
UPDATE feeds
SET name = $1, keywords = $2, modified_at = CURRENT_TIMESTAMP
WHERE id = $3 AND user_id = $4 AND status = TRUE AND removed_at IS NULL
RETURNING id, status, name, keywords, user_id, created_at, modified_at, removed_at
`

type UpdateFeedByIDAndUserParams struct {
	Name     string          `json:"name"`
	Keywords json.RawMessage `json:"keywords"`
	ID       string          `json:"id"`
	UserID   string          `json:"user_id"`
}

func (q *Queries) UpdateFeedByIDAndUser(ctx context.Context, arg UpdateFeedByIDAndUserParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, updateFeedByIDAndUser,
		arg.Name,
		arg.Keywords,
		arg.ID,
		arg.UserID,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Name,
		&i.Keywords,
		&i.UserID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.RemovedAt,
	)
	return i, err
}
