// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feeds.sql

package db

import (
	"context"
)

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds (id, name, keywords, user_id)
VALUES (?, ?, ?, ?)
RETURNING id, status, name, keywords, user_id, created_at, modified_at, removed_at
`

type CreateFeedParams struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Keywords string `json:"keywords"`
	UserID   string `json:"user_id"`
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed,
		arg.ID,
		arg.Name,
		arg.Keywords,
		arg.UserID,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Name,
		&i.Keywords,
		&i.UserID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.RemovedAt,
	)
	return i, err
}

const findFeedByIDAndUser = `-- name: FindFeedByIDAndUser :one
SELECT id, status, name, keywords, user_id, created_at, modified_at, removed_at FROM feeds
WHERE id = ? AND user_id = ? AND status = 1 AND removed_at IS NULL
LIMIT 1
`

type FindFeedByIDAndUserParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) FindFeedByIDAndUser(ctx context.Context, arg FindFeedByIDAndUserParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, findFeedByIDAndUser, arg.ID, arg.UserID)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Name,
		&i.Keywords,
		&i.UserID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.RemovedAt,
	)
	return i, err
}

const listFeedsByUser = `-- name: ListFeedsByUser :many
SELECT id, status, name, keywords, user_id, created_at, modified_at, removed_at FROM feeds
WHERE user_id = ? AND status = 1 AND removed_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListFeedsByUser(ctx context.Context, userID string) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, listFeedsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Name,
			&i.Keywords,
			&i.UserID,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.RemovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countActiveFeedsByUser = `-- name: CountActiveFeedsByUser :one
SELECT COUNT(*) FROM feeds
WHERE user_id = ? AND status = 1 AND removed_at IS NULL
`

func (q *Queries) CountActiveFeedsByUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveFeedsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateFeedByIDAndUser = `-- name: UpdateFeedByIDAndUser :one
UPDATE feeds
SET name = ?, keywords = ?, modified_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ? AND status = 1 AND removed_at IS NULL
RETURNING id, status, name, keywords, user_id, created_at, modified_at, removed_at
`

type UpdateFeedByIDAndUserParams struct {
	Name     string `json:"name"`
	Keywords string `json:"keywords"`
	ID       string `json:"id"`
	UserID   string `json:"user_id"`
}

func (q *Queries) UpdateFeedByIDAndUser(ctx context.Context, arg UpdateFeedByIDAndUserParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, updateFeedByIDAndUser,
		arg.Name,
		arg.Keywords,
		arg.ID,
		arg.UserID,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Name,
		&i.Keywords,
		&i.UserID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.RemovedAt,
	)
	return i, err
}

const softDeleteFeedByIDAndUser = `-- name: SoftDeleteFeedByIDAndUser :exec
UPDATE feeds
SET status = 0, removed_at = CURRENT_TIMESTAMP, modified_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ? AND removed_at IS NULL
`

type SoftDeleteFeedByIDAndUserParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) SoftDeleteFeedByIDAndUser(ctx context.Context, arg SoftDeleteFeedByIDAndUserParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteFeedByIDAndUser, arg.ID, arg.UserID)
	return err
}

const softDeleteFeedsByUser = `-- name: SoftDeleteFeedsByUser :exec
UPDATE feeds
SET status = 0, removed_at = CURRENT_TIMESTAMP, modified_at = CURRENT_TIMESTAMP
WHERE user_id = ? AND removed_at IS NULL
`

func (q *Queries) SoftDeleteFeedsByUser(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, softDeleteFeedsByUser, userID)
	return err
}
