// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type RefreshToken struct {
	ID         string       `json:"id"`
	UserID     string       `json:"user_id"`
	Status     int64        `json:"status"`
	ExpiresAt  time.Time    `json:"expires_at"`
	CreatedAt  time.Time    `json:"created_at"`
	ModifiedAt sql.NullTime `json:"modified_at"`
	RemovedAt  sql.NullTime `json:"removed_at"`
}

type User struct {
	ID          string         `json:"id"`
	GoogleID    string         `json:"google_id"`
	Email       string         `json:"email"`
	Name        string         `json:"name"`
	Picture     sql.NullString `json:"picture"`
	Status      int64          `json:"status"`
	LastLoginAt sql.NullTime   `json:"last_login_at"`
	CreatedAt   time.Time      `json:"created_at"`
	ModifiedAt  sql.NullTime   `json:"modified_at"`
	RemovedAt   sql.NullTime   `json:"removed_at"`
}

type UserPreference struct {
	ID               string       `json:"id"`
	UserID           string       `json:"user_id"`
	Status           int64        `json:"status"`
	Theme            string       `json:"theme"`
	Language         string       `json:"language"`
	TranslateContent int64        `json:"translate_content"`
	AiPersonality    string       `json:"ai_personality"`
	CreatedAt        time.Time    `json:"created_at"`
	ModifiedAt       sql.NullTime `json:"modified_at"`
	RemovedAt        sql.NullTime `json:"removed_at"`
}

type Source struct {
	ID         string       `json:"id"`
	Status     int64        `json:"status"`
	Url        string       `json:"url"`
	UrlRss     string       `json:"url_rss"`
	CreatedAt  time.Time    `json:"created_at"`
	ModifiedAt sql.NullTime `json:"modified_at"`
	RemovedAt  sql.NullTime `json:"removed_at"`
}

type Article struct {
	ID          string       `json:"id"`
	Status      int64        `json:"status"`
	Title       string       `json:"title"`
	Content     string       `json:"content"`
	UrlOriginal string       `json:"url_original"`
	Keywords    string       `json:"keywords"`
	CreatedAt   time.Time    `json:"created_at"`
	ModifiedAt  sql.NullTime `json:"modified_at"`
	RemovedAt   sql.NullTime `json:"removed_at"`
}
