// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
	"encoding/json"
)

type Querier interface {
	CountActiveFeedsByUser(ctx context.Context, userID string) (int64, error)
	// Counts the unread articles of every active feed owned by the user, for the
	// check-for-new-articles poll endpoint. A junction record only counts when BOTH sides are active
	// (the feed and the article), matching junction-validity rules, and only unread rows are counted.
	// The inner joins plus the is_read filter mean a feed with no unread articles produces no group and
	// is simply absent from the result (the caller renders it as no news). NOTE: keep this comment ASCII
	// only -- sqlc miscounts multibyte UTF-8 bytes here and truncates the tail of the SQL.
	CountUnreadArticlesByFeedForUser(ctx context.Context, userID string) ([]CountUnreadArticlesByFeedForUserRow, error)
	CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error)
	CreateArticleFeed(ctx context.Context, arg CreateArticleFeedParams) (ArticlesFeed, error)
	CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateSource(ctx context.Context, arg CreateSourceParams) (Source, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserPreferences(ctx context.Context, arg CreateUserPreferencesParams) (UserPreference, error)
	ExtendRefreshToken(ctx context.Context, arg ExtendRefreshTokenParams) error
	FindArticleByID(ctx context.Context, id string) (Article, error)
	FindArticleByURLOriginal(ctx context.Context, urlOriginal string) (Article, error)
	// Returns all valid articles_feeds records for an article that belong to the requesting
	// user. A junction record is only valid when BOTH related rows are active, so the joins
	// filter inactive feeds AND inactive articles (soft-deleted). is_read state is preserved
	// on the rows themselves; they just become invisible while a related side is inactive.
	FindArticleFeedsByArticleAndUser(ctx context.Context, arg FindArticleFeedsByArticleAndUserParams) ([]ArticlesFeed, error)
	// Judgement layer 1 (keyword overlap): returns every active feed (of any user) that shares at
	// least one keyword with the article, along with overlap_count (how many distinct keywords matched).
	// Both sides are JSONB arrays of lowercase strings, so jsonb_array_elements_text expands each into
	// rows and the join matches on exact keyword equality. The LATERAL is what lets the expansion of
	// f.keywords reference the feed row being scanned; the article's side does not depend on the row, so
	// it is a plain join. GROUP BY collapses a feed to one row and COUNT gives its overlap (grouping by
	// f.id alone is valid because it is the primary key, so the other f.* columns are functionally
	// dependent on it). The overlap feeds the triage (auto-associate / discard / send-to-AI) in layer 2.
	// The parameter is the article's keywords as a JSON array.
	FindCandidateFeedsByKeywords(ctx context.Context, keywords json.RawMessage) ([]FindCandidateFeedsByKeywordsRow, error)
	FindFeedByIDAndUser(ctx context.Context, arg FindFeedByIDAndUserParams) (Feed, error)
	FindRefreshTokenByID(ctx context.Context, id string) (RefreshToken, error)
	FindSourceByID(ctx context.Context, id string) (Source, error)
	FindUserByGoogleID(ctx context.Context, googleID string) (User, error)
	FindUserByID(ctx context.Context, id string) (User, error)
	FindUserPreferencesByUserID(ctx context.Context, userID string) (UserPreference, error)
	GetSystem(ctx context.Context) (System, error)
	ListArticles(ctx context.Context) ([]Article, error)
	// Returns the active articles associated with a feed, each with its is_read state for that feed
	// and its source's data (always joined, cheap PK lookup, but only mapped into the response when
	// ?with_sources=true, per conventions.md). The article's source is guaranteed active: soft-deleting
	// a source cascades to soft-delete its articles, so an active article always has an active source.
	// Both the feed and the article sides of the junction must be active, and the feed must belong to
	// the requesting user, so another user's feed yields no rows. The caller checks feed ownership
	// separately to distinguish "feed not found / not yours" (404) from "feed has no articles" (200).
	// Ordered newest-first; is_read / date filtering and pagination are applied by the caller.
	ListArticlesByFeedForUser(ctx context.Context, arg ListArticlesByFeedForUserParams) ([]ListArticlesByFeedForUserRow, error)
	ListFeedsByUser(ctx context.Context, userID string) ([]Feed, error)
	ListSources(ctx context.Context) ([]Source, error)
	// Marks is_read on all unread articles_feeds records for a given article and user.
	// Idempotent: already-read records are not touched. Both related rows must be active:
	// the article and the feed.
	MarkArticleAsReadForUser(ctx context.Context, arg MarkArticleAsReadForUserParams) error
	RevokeAllRefreshTokensByUserID(ctx context.Context, userID string) error
	RevokeRefreshToken(ctx context.Context, id string) error
	SoftDeleteArticle(ctx context.Context, id string) error
	SoftDeleteArticlesBySourceID(ctx context.Context, sourceID string) error
	SoftDeleteFeedByIDAndUser(ctx context.Context, arg SoftDeleteFeedByIDAndUserParams) error
	SoftDeleteFeedsByUser(ctx context.Context, userID string) error
	SoftDeleteSource(ctx context.Context, id string) error
	SoftDeleteUser(ctx context.Context, id string) error
	SoftDeleteUserPreferences(ctx context.Context, userID string) error
	UpdateArticle(ctx context.Context, arg UpdateArticleParams) (Article, error)
	UpdateFeedByIDAndUser(ctx context.Context, arg UpdateFeedByIDAndUserParams) (Feed, error)
	UpdateSource(ctx context.Context, arg UpdateSourceParams) (Source, error)
	UpdateSystemAppStatus(ctx context.Context, appStatus bool) (System, error)
	UpdateSystemLastArticleDiscovery(ctx context.Context, lastArticleDiscoveryAt sql.NullTime) (System, error)
	UpdateUserLastLogin(ctx context.Context, id string) error
	UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) (UserPreference, error)
}

var _ Querier = (*Queries)(nil)
