// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"

	utctime "github.com/nathanap/news-feed-backend/services/utctime"
)

type Querier interface {
	// Counts every active feed of a user, enforcing the max-active-feeds business rule at creation
	// time. Intentionally unfiltered: the limit is about how many feeds exist, not about a search.
	CountActiveFeedsByUser(ctx context.Context, userID string) (int64, error)
	// Total matching rows for the ListArticles page, feeding pagination.total_count.
	// Its filters MUST mirror ListArticles above, or the envelope lies about the total.
	CountArticles(ctx context.Context, url sql.NullString) (int64, error)
	// Total matching rows for the ListArticlesByFeedForUser page, feeding pagination.total_count.
	// Its joins and filters MUST mirror ListArticlesByFeedForUser above, or the envelope lies about the
	// total. The sources join is kept even though no source column is selected: it is what enforces
	// "an article of an inactive source does not count", matching the list exactly.
	CountArticlesByFeedForUser(ctx context.Context, arg CountArticlesByFeedForUserParams) (int64, error)
	// Total matching rows for the ListFeedsByUser page, feeding pagination.total_count.
	// Its filters MUST mirror ListFeedsByUser above, or the envelope lies about the total.
	// NOTE: this is NOT the query that guards the 5-active-feeds-per-user rule -- that one is
	// CountActiveFeedsByUser below, which must never see a name filter.
	CountFeedsByUser(ctx context.Context, arg CountFeedsByUserParams) (int64, error)
	// Total matching rows for the ListSources page, feeding pagination.total_count.
	// Its filters MUST mirror ListSources above, or the envelope lies about the total.
	CountSources(ctx context.Context, arg CountSourcesParams) (int64, error)
	// Counts the unread articles of every active feed owned by the user, for the
	// check-for-new-articles poll endpoint. A junction record only counts when BOTH sides are active
	// (the feed and the article), matching junction-validity rules, and only unread rows are counted.
	// The inner joins plus the is_read filter mean a feed with no unread articles produces no group and
	// is simply absent from the result (the caller renders it as no news). NOTE: keep this comment ASCII
	// only -- sqlc miscounts multibyte UTF-8 bytes here and truncates the tail of the SQL.
	CountUnreadArticlesByFeedForUser(ctx context.Context, userID string) ([]CountUnreadArticlesByFeedForUserRow, error)
	CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error)
	CreateArticleFeed(ctx context.Context, arg CreateArticleFeedParams) (ArticlesFeed, error)
	// One row per distinct href found in a freshly persisted article body (see the outboundlinks service).
	// href is the real target: an internal link as the literal token `{CLIENT_URL}/articles/{id}`, an
	// external link literally. The body stores this row's id in the anchor, never the URL.
	CreateArticleOutboundLink(ctx context.Context, arg CreateArticleOutboundLinkParams) (ArticleOutboundLink, error)
	CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateSource(ctx context.Context, arg CreateSourceParams) (Source, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserPreferences(ctx context.Context, arg CreateUserPreferencesParams) (UserPreference, error)
	// Hard-delete cascade for an article hard-remove. Dormant today (articles are only soft-removed) but
	// kept ready in code, per the project's cascade philosophy.
	DeleteArticleOutboundLinksByArticleID(ctx context.Context, articleID string) error
	ExtendRefreshToken(ctx context.Context, arg ExtendRefreshTokenParams) error
	FindArticleByID(ctx context.Context, id string) (Article, error)
	FindArticleByURLOriginal(ctx context.Context, urlOriginal string) (Article, error)
	// Returns all valid articles_feeds records for an article that belong to the requesting
	// user. A junction record is only valid when BOTH related rows are active, so the joins
	// filter inactive feeds AND inactive articles (soft-deleted). is_read state is preserved
	// on the rows themselves; they just become invisible while a related side is inactive.
	FindArticleFeedsByArticleAndUser(ctx context.Context, arg FindArticleFeedsByArticleAndUserParams) ([]ArticlesFeed, error)
	// Judgement layer 1 (keyword overlap): returns every active feed (of any user) that shares at
	// least one keyword with the article, along with overlap_count (how many distinct keywords matched).
	// Restricted to feeds owned by an ACTIVE user (0.43): the join to users drops feeds whose owner has
	// not been seen within inactive_days, so the CRON stops routing news (and paying for AI) to abandoned
	// accounts. inactive_days = -1 disables the window (every user counts as active); a positive N means
	// last_active_at must be within N days. The owner must also be active (status/removed_at) like every
	// other related lookup. Judgement is not retroactive, so an account that comes back has permanently
	// missed the articles discovered while it was inactive - this is the accepted trade-off.
	// Both sides are JSONB arrays of lowercase strings, so jsonb_array_elements_text expands each into
	// rows and the join matches on exact keyword equality. The LATERAL is what lets the expansion of
	// f.keywords reference the feed row being scanned; the article's side does not depend on the row, so
	// it is a plain join. GROUP BY collapses a feed to one row and COUNT gives its overlap (grouping by
	// f.id alone is valid because it is the primary key, so the other f.* columns are functionally
	// dependent on it). The overlap feeds the triage (auto-associate / discard / send-to-AI) in layer 2.
	// The parameter is the article's keywords as a text[] (see the planner note below).
	//
	// The `?|` predicate ("does f.keywords contain ANY of these keys") is what makes idx_feeds_keywords
	// (GIN) REACHABLE: an index is matched by OPERATOR, and expanding a column through
	// jsonb_array_elements_text in a LATERAL is a function call on every row, which no index can serve.
	// Without it the planner reads every active feed of every user and expands its keywords just to
	// throw almost all of them away (0.37.3 measured 428ms/10.2k buffers versus 22ms/836 with it, on 60k
	// feeds).
	//
	// Reachable is not the same as CHOSEN, and reading the paragraph above as a guarantee is what hid a
	// bug for seven versions - see the note on the text[] parameter further down, which is the other half
	// of the condition.
	//
	// It is logically redundant with the join below (a feed with zero shared keywords produces no row
	// either way), so it cannot change the result set - it only lets the planner discard non-candidates
	// before the expensive expansion. It must be kept in sync with the join's matching rule: both sides
	// compare the same lowercase text keys.
	//
	// keywords is a text[] and NOT a JSON array, and that is what makes the index choice reliable
	// (0.46.4). The right operator is necessary but not sufficient: written as
	// `?| ARRAY(SELECT jsonb_array_elements_text($1::jsonb))` the operand is an InitPlan, opaque at plan
	// time, so the planner cannot estimate its selectivity, defaults to a guess, and prices the index
	// above a seq scan. That makes index usage depend on table size and flip on its own as the table
	// grows - the 428ms -> 22ms win measured on 60k feeds in 0.37.3 was real at that volume, but it was
	// never guaranteed. Measured on the mirrored articles query at 20k rows, the same shape planned a
	// Seq Scan while `?| $1::text[]` planned a Bitmap Index Scan. Passing text[] makes the estimate
	// correct and the choice deterministic, and it also drops a jsonb round-trip the caller was paying
	// for nothing (the controller already holds a []string). Do not turn this back into jsonb.
	FindCandidateFeedsByKeywords(ctx context.Context, arg FindCandidateFeedsByKeywordsParams) ([]FindCandidateFeedsByKeywordsRow, error)
	FindFeedByIDAndUser(ctx context.Context, arg FindFeedByIDAndUserParams) (Feed, error)
	FindRefreshTokenByID(ctx context.Context, id string) (RefreshToken, error)
	FindSourceByID(ctx context.Context, id string) (Source, error)
	FindUserByGoogleID(ctx context.Context, googleID string) (User, error)
	FindUserByID(ctx context.Context, id string) (User, error)
	FindUserPreferencesByUserID(ctx context.Context, userID string) (UserPreference, error)
	GetSystem(ctx context.Context) (System, error)
	// Every active article, unfiltered and unpaginated, for the dev seed scripts (which need the whole
	// set to build article/feed associations). See ListAllSources for why this is separate from the
	// paginated ListArticles that serves HTTP.
	ListAllArticles(ctx context.Context) ([]Article, error)
	// Every active feed of a user, unfiltered and unpaginated, for the dev seed scripts. See
	// ListAllSources for why this is separate from the paginated ListFeedsByUser that serves HTTP.
	ListAllFeedsByUser(ctx context.Context, userID string) ([]Feed, error)
	// Every active source, unfiltered and unpaginated, for the internal batch consumers: the CRON's
	// discovery sweep (which must visit ALL sources, not a page of them) and the dev seed scripts.
	// Deliberately separate from ListSources: paging a sweep would silently skip sources, and giving
	// the batch callers a page_size big enough to "fit everything" would be a bug waiting for the
	// source count to grow past it. HTTP clients must use ListSources, which is always paginated.
	ListAllSources(ctx context.Context) ([]Source, error)
	// Every outbound link of the given articles, in one batch, for the read-time swap. The listing/read
	// endpoints pass the ids of the whole page here (never one query per article - no N+1).
	// Stays on ANY(...::text[]) even though it makes sqlc emit pq.Array, which is the only reason lib/pq
	// is still a dependency alongside the real driver (pgx). Do NOT "clean this up" with sqlc.slice:
	// tried in 0.46 and it is broken for the postgresql engine - sqlc renders the placeholder as `$1`,
	// losing the /*SLICE:*/ marker its own generated strings.Replace looks for, and then builds MySQL
	// style `?` placeholders. Result compiles and passes any test that sends a single id, but fails at
	// runtime as soon as a page carries two (bind message supplies N parameters, statement requires 1).
	ListArticleOutboundLinksByArticleIDs(ctx context.Context, articleIds []string) ([]ArticleOutboundLink, error)
	// Lists the active articles for GET /v1/articles, filtered and paginated in SQL.
	// The url filter is optional: a NULL param means "no filter" (sqlc.narg), so one query serves both
	// the filtered and the unfiltered case. strpos(lower(a), lower(b)) > 0 is a literal case-insensitive
	// substring test -- deliberately not ILIKE '%...%', which would let a user's % or _ act as wildcards.
	// Neither can use an index (leading wildcard); pg_trgm is the path if that ever matters.
	// id breaks created_at ties so the ordering is total: without it, rows written in the same CRON
	// batch share a timestamp and LIMIT/OFFSET could repeat or skip one across pages. id is a UUIDv7,
	// so it sorts by creation time and the tie-break stays chronological.
	// CountArticles below MUST keep the same filters.
	ListArticles(ctx context.Context, arg ListArticlesParams) ([]Article, error)
	// Returns the active articles associated with a feed, each with its is_read state for that feed
	// and its source's data (always joined, cheap PK lookup, but only mapped into the response when
	// ?with_sources=true, per conventions.md). The article's source is guaranteed active: soft-deleting
	// a source cascades to soft-delete its articles, so an active article always has an active source.
	// Both the feed and the article sides of the junction must be active, and the feed must belong to
	// the requesting user, so another user's feed yields no rows. The caller checks feed ownership
	// separately to distinguish "feed not found / not yours" (404) from "feed has no articles" (200).
	// Filtered and paginated in SQL. All three filters are optional (NULL = not applied): is_read, and
	// the created_at window, whose bounds are independent and inclusive on both ends.
	// Ordered newest-first, with a.id breaking created_at ties so the ordering is total: without it,
	// articles written in the same CRON batch share a timestamp and LIMIT/OFFSET could repeat or skip
	// one across pages. id is a UUIDv7, so the tie-break stays chronological.
	// CountArticlesByFeedForUser below MUST keep the same joins and filters.
	ListArticlesByFeedForUser(ctx context.Context, arg ListArticlesByFeedForUserParams) ([]ListArticlesByFeedForUserRow, error)
	// Lists the requesting user's active feeds for GET /v1/feeds, filtered and paginated in SQL.
	// The name filter is optional (NULL = not applied). See ListArticles for why strpos over ILIKE and
	// why id breaks the created_at tie. CountFeedsByUser below MUST keep the same filters.
	ListFeedsByUser(ctx context.Context, arg ListFeedsByUserParams) ([]Feed, error)
	// Lists the active sources for GET /v1/sources, filtered and paginated in SQL.
	// url and name are independent optional substring filters (NULL = not applied); passing both ANDs
	// them. See ListArticles for why strpos over ILIKE and why id breaks the created_at tie.
	// CountSources below MUST keep the same filters.
	ListSources(ctx context.Context, arg ListSourcesParams) ([]Source, error)
	// Marks is_read on all unread articles_feeds records for a given article and user.
	// Idempotent: already-read records are not touched. Both related rows must be active:
	// the article and the feed.
	MarkArticleAsReadForUser(ctx context.Context, arg MarkArticleAsReadForUserParams) error
	// Repoints every row currently pointing at old_href to new_href. Two callers, both matching by exact
	// href (idx_article_outbound_links_href):
	//   * retroactive linking: when article B is persisted, old_href = B.url_original, new_href =
	//     `{CLIENT_URL}/articles/{B.id}` — older articles that linked B's external URL now open internally.
	//   * pre-remove cleanup: before an article L is removed, old_href = `{CLIENT_URL}/articles/{L.id}`,
	//     new_href = L.url_original — links pointing at the vanishing internal page fall back to the source.
	RetargetArticleOutboundLinksByHref(ctx context.Context, arg RetargetArticleOutboundLinksByHrefParams) error
	// Cascade counterpart of RetargetArticleOutboundLinksByHref, for the source soft-delete (0.48.3).
	// Soft-deleting a source cascades to its articles, and a cascaded article is still a removed article:
	// every outbound link pointing at its internal page has to fall back to the source URL, or older
	// articles keep anchors to a page that answers 404. The single-article delete path had this since
	// 0.46.1; the cascade path did not, which is the gap this closes.
	//
	// Set-based on purpose: one statement instead of one Retarget per article. A source can own a lot of
	// articles, and an N+1 inside the deletion transaction is the wrong shape.
	//
	// internal_href_prefix is `{CLIENT_URL}/articles/` supplied by Go (outboundlinks.InternalHrefPrefix),
	// so the token format stays owned by the outboundlinks package instead of being duplicated in SQL.
	RetargetArticleOutboundLinksBySourceID(ctx context.Context, arg RetargetArticleOutboundLinksBySourceIDParams) error
	RevokeAllRefreshTokensByUserID(ctx context.Context, userID string) error
	RevokeRefreshToken(ctx context.Context, id string) error
	// SetUserAdmin is deliberately separate from CreateUser instead of an `admin` parameter on it: the
	// Google login flow is the only caller of CreateUser, and keeping the column out of that INSERT makes
	// it structurally impossible for a login to mint an administrator. Promotion is an explicit, separate
	// act. Today only the development seed calls this; a future admin-management endpoint would too.
	SetUserAdmin(ctx context.Context, arg SetUserAdminParams) (User, error)
	SoftDeleteArticle(ctx context.Context, id string) error
	SoftDeleteArticlesBySourceID(ctx context.Context, sourceID string) error
	SoftDeleteFeedByIDAndUser(ctx context.Context, arg SoftDeleteFeedByIDAndUserParams) error
	SoftDeleteFeedsByUser(ctx context.Context, userID string) error
	SoftDeleteSource(ctx context.Context, id string) error
	SoftDeleteUser(ctx context.Context, id string) error
	SoftDeleteUserPreferences(ctx context.Context, userID string) error
	// Keyword suggestions, "popular" strategy: the keywords carried by the most active articles inside a
	// recency window, for the feed-building keyword-suggestion endpoint. This is the fallback path (used
	// when nothing is selected yet, or when the "related" query came back empty), so it must always be
	// able to return something as long as the window holds any article.
	// LATERAL expands each active article's keyword array into rows; COUNT per distinct keyword is how
	// many articles carry it (keywords are unique within an article, so one row per article-keyword).
	// The window (created_at >= since) is what makes "popular" mean "popular right now" and keeps the
	// full-table aggregation bounded; the caller passes the epoch when the window is disabled.
	// exclude is the caller's already-picked keywords as a JSON array (empty = exclude nothing, since
	// value <> ALL(empty) is TRUE); no point suggesting a keyword the user already has.
	// Ordered by count, then keyword for a stable, deterministic tie-break (same lesson as the 0.38 lists).
	SuggestPopularKeywords(ctx context.Context, arg SuggestPopularKeywordsParams) ([]SuggestPopularKeywordsRow, error)
	// Keyword suggestions, "related" strategy: keywords that co-occur with the ones the user already
	// picked. Narrows to articles that carry ANY selected keyword (keywords ?| selected), then counts
	// the OTHER keywords those articles carry. Deliberately not windowed (unlike popular): relatedness is
	// topical, not temporal, and a window would only make the empty-result fallback fire more often for a
	// niche pick.
	// The `?|` predicate is what reaches idx_articles_keywords (GIN): it is applied as a row filter that
	// narrows which articles get expanded, exactly the shape the 0.37.3 review established. Keep it in
	// sync with that index. selected drives both the narrowing (which articles) and the exclusion (never
	// suggest back a keyword the user already picked).
	//
	// selected is a text[] and NOT a JSON array, and that is a planner decision, not a style one (0.46.4).
	// Reaching a GIN index needs more than the right operator: the right-hand side must also be something
	// the planner can estimate. Written as `?| ARRAY(SELECT jsonb_array_elements_text($1::jsonb))` the
	// operand is an InitPlan, opaque at plan time, so the planner falls back to a default selectivity and
	// prices the index above a seq scan. Measured on 20k articles: the ARRAY(SELECT ...) form planned a
	// Seq Scan (cost 677, 19999 rows discarded by filter) while `?| $1::text[]` planned a Bitmap Index
	// Scan (cost 433). Forcing enable_seqscan=off proved the index was usable either way - the planner
	// simply would not choose it. Do not "simplify" this back into a jsonb subquery.
	SuggestRelatedKeywords(ctx context.Context, arg SuggestRelatedKeywordsParams) ([]SuggestRelatedKeywordsRow, error)
	UpdateArticle(ctx context.Context, arg UpdateArticleParams) (Article, error)
	// Overwrites only the body, for the 0.45 treatment DB step: right after an article is stored, its
	// anchors are rewritten to outbound-link ids and the body is written back. Keeps title/keywords/etc.
	// untouched (unlike UpdateArticle). Runs inside the same transaction as the insert.
	UpdateArticleContent(ctx context.Context, arg UpdateArticleContentParams) error
	UpdateFeedByIDAndUser(ctx context.Context, arg UpdateFeedByIDAndUserParams) (Feed, error)
	UpdateSource(ctx context.Context, arg UpdateSourceParams) (Source, error)
	UpdateSystemAppStatus(ctx context.Context, appStatus bool) (System, error)
	UpdateSystemLastArticleDiscovery(ctx context.Context, lastArticleDiscoveryAt utctime.NullTime) (System, error)
	// UpdateUserLastActive stamps the user's activity heartbeat. Called on every /auth/refresh (the
	// hourly ping) and on login. This is the signal the discovery filter reads to skip inactive users.
	UpdateUserLastActive(ctx context.Context, id string) error
	UpdateUserLastLogin(ctx context.Context, id string) error
	UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) (UserPreference, error)
}

var _ Querier = (*Queries)(nil)
