// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package db

import (
	"context"
	"time"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (id, user_id, expires_at)
VALUES (?, ?, ?)
RETURNING id, user_id, status, expires_at, created_at, modified_at, removed_at
`

type CreateRefreshTokenParams struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createRefreshToken, arg.ID, arg.UserID, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.RemovedAt,
	)
	return i, err
}

const extendRefreshToken = `-- name: ExtendRefreshToken :exec
UPDATE refresh_tokens
SET expires_at = ?, modified_at = CURRENT_TIMESTAMP
WHERE id = ? AND status = 1 AND removed_at IS NULL
`

type ExtendRefreshTokenParams struct {
	ExpiresAt time.Time `json:"expires_at"`
	ID        string    `json:"id"`
}

func (q *Queries) ExtendRefreshToken(ctx context.Context, arg ExtendRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, extendRefreshToken, arg.ExpiresAt, arg.ID)
	return err
}

const findRefreshTokenByID = `-- name: FindRefreshTokenByID :one
SELECT id, user_id, status, expires_at, created_at, modified_at, removed_at FROM refresh_tokens
WHERE id = ? AND status = 1 AND removed_at IS NULL
LIMIT 1
`

func (q *Queries) FindRefreshTokenByID(ctx context.Context, id string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, findRefreshTokenByID, id)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.RemovedAt,
	)
	return i, err
}

const revokeAllRefreshTokensByUserID = `-- name: RevokeAllRefreshTokensByUserID :exec
UPDATE refresh_tokens
SET status = 0, removed_at = CURRENT_TIMESTAMP, modified_at = CURRENT_TIMESTAMP
WHERE user_id = ? AND removed_at IS NULL
`

func (q *Queries) RevokeAllRefreshTokensByUserID(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, revokeAllRefreshTokensByUserID, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET status = 0, removed_at = CURRENT_TIMESTAMP, modified_at = CURRENT_TIMESTAMP
WHERE id = ? AND removed_at IS NULL
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshToken, id)
	return err
}
