// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

const createSource = `-- name: CreateSource :one
INSERT INTO sources (id, url, url_rss)
VALUES (?, ?, ?)
RETURNING id, status, url, url_rss, created_at, modified_at, removed_at
`

type CreateSourceParams struct {
	ID     string `json:"id"`
	Url    string `json:"url"`
	UrlRss string `json:"url_rss"`
}

func (q *Queries) CreateSource(ctx context.Context, arg CreateSourceParams) (Source, error) {
	row := q.db.QueryRowContext(ctx, createSource, arg.ID, arg.Url, arg.UrlRss)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Url,
		&i.UrlRss,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.RemovedAt,
	)
	return i, err
}

const findSourceByID = `-- name: FindSourceByID :one
SELECT id, status, url, url_rss, created_at, modified_at, removed_at FROM sources
WHERE id = ? AND removed_at IS NULL
LIMIT 1
`

func (q *Queries) FindSourceByID(ctx context.Context, id string) (Source, error) {
	row := q.db.QueryRowContext(ctx, findSourceByID, id)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Url,
		&i.UrlRss,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.RemovedAt,
	)
	return i, err
}

const listSources = `-- name: ListSources :many
SELECT id, status, url, url_rss, created_at, modified_at, removed_at FROM sources
WHERE removed_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListSources(ctx context.Context) ([]Source, error) {
	rows, err := q.db.QueryContext(ctx, listSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []Source
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Url,
			&i.UrlRss,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.RemovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSource = `-- name: UpdateSource :one
UPDATE sources
SET url = ?, url_rss = ?, modified_at = CURRENT_TIMESTAMP
WHERE id = ? AND removed_at IS NULL
RETURNING id, status, url, url_rss, created_at, modified_at, removed_at
`

type UpdateSourceParams struct {
	Url    string `json:"url"`
	UrlRss string `json:"url_rss"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateSource(ctx context.Context, arg UpdateSourceParams) (Source, error) {
	row := q.db.QueryRowContext(ctx, updateSource, arg.Url, arg.UrlRss, arg.ID)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Url,
		&i.UrlRss,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.RemovedAt,
	)
	return i, err
}

const softDeleteSource = `-- name: SoftDeleteSource :exec
UPDATE sources
SET status = 0, removed_at = CURRENT_TIMESTAMP, modified_at = CURRENT_TIMESTAMP
WHERE id = ? AND removed_at IS NULL
`

func (q *Queries) SoftDeleteSource(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, softDeleteSource, id)
	return err
}
