// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sources.sql

package db

import (
	"context"
	"database/sql"
)

const countSources = `-- name: CountSources :one
SELECT COUNT(*) FROM sources
WHERE status = TRUE AND removed_at IS NULL
  AND ($1::text IS NULL OR strpos(lower(url), lower($1::text)) > 0)
  AND ($2::text IS NULL OR strpos(lower(name), lower($2::text)) > 0)
`

type CountSourcesParams struct {
	Url  sql.NullString `json:"url"`
	Name sql.NullString `json:"name"`
}

// Total matching rows for the ListSources page, feeding pagination.total_count.
// Its filters MUST mirror ListSources above, or the envelope lies about the total.
func (q *Queries) CountSources(ctx context.Context, arg CountSourcesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSources, arg.Url, arg.Name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSource = `-- name: CreateSource :one
INSERT INTO sources (id, name, url, url_rss)
VALUES ($1, $2, $3, $4)
RETURNING id, status, name, url, url_rss, created_at, modified_at, removed_at
`

type CreateSourceParams struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Url    string `json:"url"`
	UrlRss string `json:"url_rss"`
}

func (q *Queries) CreateSource(ctx context.Context, arg CreateSourceParams) (Source, error) {
	row := q.db.QueryRowContext(ctx, createSource,
		arg.ID,
		arg.Name,
		arg.Url,
		arg.UrlRss,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Name,
		&i.Url,
		&i.UrlRss,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.RemovedAt,
	)
	return i, err
}

const findSourceByID = `-- name: FindSourceByID :one
SELECT id, status, name, url, url_rss, created_at, modified_at, removed_at FROM sources
WHERE id = $1 AND status = TRUE AND removed_at IS NULL
LIMIT 1
`

func (q *Queries) FindSourceByID(ctx context.Context, id string) (Source, error) {
	row := q.db.QueryRowContext(ctx, findSourceByID, id)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Name,
		&i.Url,
		&i.UrlRss,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.RemovedAt,
	)
	return i, err
}

const listAllSources = `-- name: ListAllSources :many
SELECT id, status, name, url, url_rss, created_at, modified_at, removed_at FROM sources
WHERE status = TRUE AND removed_at IS NULL
ORDER BY created_at DESC, id DESC
`

// Every active source, unfiltered and unpaginated, for the internal batch consumers: the CRON's
// discovery sweep (which must visit ALL sources, not a page of them) and the dev seed scripts.
// Deliberately separate from ListSources: paging a sweep would silently skip sources, and giving
// the batch callers a page_size big enough to "fit everything" would be a bug waiting for the
// source count to grow past it. HTTP clients must use ListSources, which is always paginated.
func (q *Queries) ListAllSources(ctx context.Context) ([]Source, error) {
	rows, err := q.db.QueryContext(ctx, listAllSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Source
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Name,
			&i.Url,
			&i.UrlRss,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.RemovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSources = `-- name: ListSources :many
SELECT id, status, name, url, url_rss, created_at, modified_at, removed_at FROM sources
WHERE status = TRUE AND removed_at IS NULL
  AND ($1::text IS NULL OR strpos(lower(url), lower($1::text)) > 0)
  AND ($2::text IS NULL OR strpos(lower(name), lower($2::text)) > 0)
ORDER BY created_at DESC, id DESC
LIMIT $4 OFFSET $3
`

type ListSourcesParams struct {
	Url        sql.NullString `json:"url"`
	Name       sql.NullString `json:"name"`
	PageOffset int32          `json:"page_offset"`
	PageLimit  int32          `json:"page_limit"`
}

// Lists the active sources for GET /v1/sources, filtered and paginated in SQL.
// url and name are independent optional substring filters (NULL = not applied); passing both ANDs
// them. See ListArticles for why strpos over ILIKE and why id breaks the created_at tie.
// CountSources below MUST keep the same filters.
func (q *Queries) ListSources(ctx context.Context, arg ListSourcesParams) ([]Source, error) {
	rows, err := q.db.QueryContext(ctx, listSources,
		arg.Url,
		arg.Name,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Source
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Name,
			&i.Url,
			&i.UrlRss,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.RemovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteSource = `-- name: SoftDeleteSource :exec
UPDATE sources
SET status = FALSE, removed_at = CURRENT_TIMESTAMP, modified_at = CURRENT_TIMESTAMP
WHERE id = $1 AND removed_at IS NULL
`

func (q *Queries) SoftDeleteSource(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, softDeleteSource, id)
	return err
}

const updateSource = `-- name: UpdateSource :one
UPDATE sources
SET name = $1, url = $2, url_rss = $3, modified_at = CURRENT_TIMESTAMP
WHERE id = $4 AND status = TRUE AND removed_at IS NULL
RETURNING id, status, name, url, url_rss, created_at, modified_at, removed_at
`

type UpdateSourceParams struct {
	Name   string `json:"name"`
	Url    string `json:"url"`
	UrlRss string `json:"url_rss"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateSource(ctx context.Context, arg UpdateSourceParams) (Source, error) {
	row := q.db.QueryRowContext(ctx, updateSource,
		arg.Name,
		arg.Url,
		arg.UrlRss,
		arg.ID,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Name,
		&i.Url,
		&i.UrlRss,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.RemovedAt,
	)
	return i, err
}
