// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system.sql

package db

import (
	"context"

	utctime "github.com/nathanap/news-feed-backend/services/utctime"
)

const getSystem = `-- name: GetSystem :one
SELECT id, app_status, last_article_discovery_at, created_at, modified_at FROM system
LIMIT 1
`

func (q *Queries) GetSystem(ctx context.Context) (System, error) {
	row := q.db.QueryRowContext(ctx, getSystem)
	var i System
	err := row.Scan(
		&i.ID,
		&i.AppStatus,
		&i.LastArticleDiscoveryAt,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const updateSystemAppStatus = `-- name: UpdateSystemAppStatus :one
UPDATE system
SET app_status = $1, modified_at = CURRENT_TIMESTAMP
RETURNING id, app_status, last_article_discovery_at, created_at, modified_at
`

func (q *Queries) UpdateSystemAppStatus(ctx context.Context, appStatus bool) (System, error) {
	row := q.db.QueryRowContext(ctx, updateSystemAppStatus, appStatus)
	var i System
	err := row.Scan(
		&i.ID,
		&i.AppStatus,
		&i.LastArticleDiscoveryAt,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const updateSystemLastArticleDiscovery = `-- name: UpdateSystemLastArticleDiscovery :one
UPDATE system
SET last_article_discovery_at = $1, modified_at = CURRENT_TIMESTAMP
RETURNING id, app_status, last_article_discovery_at, created_at, modified_at
`

func (q *Queries) UpdateSystemLastArticleDiscovery(ctx context.Context, lastArticleDiscoveryAt utctime.NullTime) (System, error) {
	row := q.db.QueryRowContext(ctx, updateSystemLastArticleDiscovery, lastArticleDiscoveryAt)
	var i System
	err := row.Scan(
		&i.ID,
		&i.AppStatus,
		&i.LastArticleDiscoveryAt,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}
