// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

const getSystem = `-- name: GetSystem :one
SELECT id, app_status, last_article_discovery_at, created_at, modified_at FROM system
LIMIT 1
`

func (q *Queries) GetSystem(ctx context.Context) (System, error) {
	row := q.db.QueryRowContext(ctx, getSystem)
	var i System
	err := row.Scan(
		&i.ID,
		&i.AppStatus,
		&i.LastArticleDiscoveryAt,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const updateSystemAppStatus = `-- name: UpdateSystemAppStatus :one
UPDATE system
SET app_status = ?, modified_at = CURRENT_TIMESTAMP
RETURNING id, app_status, last_article_discovery_at, created_at, modified_at
`

func (q *Queries) UpdateSystemAppStatus(ctx context.Context, appStatus int64) (System, error) {
	row := q.db.QueryRowContext(ctx, updateSystemAppStatus, appStatus)
	var i System
	err := row.Scan(
		&i.ID,
		&i.AppStatus,
		&i.LastArticleDiscoveryAt,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}
