// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_preferences.sql

package db

import (
	"context"
)

const createUserPreferences = `-- name: CreateUserPreferences :one
INSERT INTO user_preferences (id, user_id, theme, language, translate_content, ai_personality)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, user_id, status, theme, language, translate_content, ai_personality, created_at, modified_at, removed_at
`

type CreateUserPreferencesParams struct {
	ID               string `json:"id"`
	UserID           string `json:"user_id"`
	Theme            string `json:"theme"`
	Language         string `json:"language"`
	TranslateContent int64  `json:"translate_content"`
	AiPersonality    string `json:"ai_personality"`
}

func (q *Queries) CreateUserPreferences(ctx context.Context, arg CreateUserPreferencesParams) (UserPreference, error) {
	row := q.db.QueryRowContext(ctx, createUserPreferences,
		arg.ID,
		arg.UserID,
		arg.Theme,
		arg.Language,
		arg.TranslateContent,
		arg.AiPersonality,
	)
	var i UserPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Theme,
		&i.Language,
		&i.TranslateContent,
		&i.AiPersonality,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.RemovedAt,
	)
	return i, err
}

const findUserPreferencesByUserID = `-- name: FindUserPreferencesByUserID :one
SELECT id, user_id, status, theme, language, translate_content, ai_personality, created_at, modified_at, removed_at FROM user_preferences
WHERE user_id = ? AND status = 1 AND removed_at IS NULL
LIMIT 1
`

func (q *Queries) FindUserPreferencesByUserID(ctx context.Context, userID string) (UserPreference, error) {
	row := q.db.QueryRowContext(ctx, findUserPreferencesByUserID, userID)
	var i UserPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Theme,
		&i.Language,
		&i.TranslateContent,
		&i.AiPersonality,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.RemovedAt,
	)
	return i, err
}

const softDeleteUserPreferences = `-- name: SoftDeleteUserPreferences :exec
UPDATE user_preferences
SET status = 0, removed_at = CURRENT_TIMESTAMP, modified_at = CURRENT_TIMESTAMP
WHERE user_id = ? AND removed_at IS NULL
`

func (q *Queries) SoftDeleteUserPreferences(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, softDeleteUserPreferences, userID)
	return err
}

const updateUserPreferences = `-- name: UpdateUserPreferences :one
UPDATE user_preferences
SET theme = ?, language = ?, translate_content = ?, ai_personality = ?,
    modified_at = CURRENT_TIMESTAMP
WHERE user_id = ? AND status = 1 AND removed_at IS NULL
RETURNING id, user_id, status, theme, language, translate_content, ai_personality, created_at, modified_at, removed_at
`

type UpdateUserPreferencesParams struct {
	Theme            string `json:"theme"`
	Language         string `json:"language"`
	TranslateContent int64  `json:"translate_content"`
	AiPersonality    string `json:"ai_personality"`
	UserID           string `json:"user_id"`
}

func (q *Queries) UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) (UserPreference, error) {
	row := q.db.QueryRowContext(ctx, updateUserPreferences,
		arg.Theme,
		arg.Language,
		arg.TranslateContent,
		arg.AiPersonality,
		arg.UserID,
	)
	var i UserPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Theme,
		&i.Language,
		&i.TranslateContent,
		&i.AiPersonality,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.RemovedAt,
	)
	return i, err
}
