// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, google_id, email, name, picture)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, google_id, email, name, picture, status, last_login_at, created_at, modified_at, removed_at, admin
`

type CreateUserParams struct {
	ID       string         `json:"id"`
	GoogleID string         `json:"google_id"`
	Email    string         `json:"email"`
	Name     string         `json:"name"`
	Picture  sql.NullString `json:"picture"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.GoogleID,
		arg.Email,
		arg.Name,
		arg.Picture,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.Picture,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.RemovedAt,
		&i.Admin,
	)
	return i, err
}

const findUserByGoogleID = `-- name: FindUserByGoogleID :one
SELECT id, google_id, email, name, picture, status, last_login_at, created_at, modified_at, removed_at, admin FROM users
WHERE google_id = $1 AND status = TRUE AND removed_at IS NULL
LIMIT 1
`

func (q *Queries) FindUserByGoogleID(ctx context.Context, googleID string) (User, error) {
	row := q.db.QueryRowContext(ctx, findUserByGoogleID, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.Picture,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.RemovedAt,
		&i.Admin,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id, google_id, email, name, picture, status, last_login_at, created_at, modified_at, removed_at, admin FROM users
WHERE id = $1 AND status = TRUE AND removed_at IS NULL
LIMIT 1
`

func (q *Queries) FindUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, findUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.Picture,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.RemovedAt,
		&i.Admin,
	)
	return i, err
}

const setUserAdmin = `-- name: SetUserAdmin :one
UPDATE users
SET admin = $2, modified_at = CURRENT_TIMESTAMP
WHERE id = $1 AND status = TRUE AND removed_at IS NULL
RETURNING id, google_id, email, name, picture, status, last_login_at, created_at, modified_at, removed_at, admin
`

type SetUserAdminParams struct {
	ID    string `json:"id"`
	Admin bool   `json:"admin"`
}

// SetUserAdmin is deliberately separate from CreateUser instead of an `admin` parameter on it: the
// Google login flow is the only caller of CreateUser, and keeping the column out of that INSERT makes
// it structurally impossible for a login to mint an administrator. Promotion is an explicit, separate
// act. Today only the development seed calls this; a future admin-management endpoint would too.
func (q *Queries) SetUserAdmin(ctx context.Context, arg SetUserAdminParams) (User, error) {
	row := q.db.QueryRowContext(ctx, setUserAdmin, arg.ID, arg.Admin)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.Picture,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.RemovedAt,
		&i.Admin,
	)
	return i, err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET status = FALSE, removed_at = CURRENT_TIMESTAMP, modified_at = CURRENT_TIMESTAMP
WHERE id = $1 AND removed_at IS NULL
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, softDeleteUser, id)
	return err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET last_login_at = CURRENT_TIMESTAMP, modified_at = CURRENT_TIMESTAMP
WHERE id = $1 AND status = TRUE AND removed_at IS NULL
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateUserLastLogin, id)
	return err
}
